### ISSUE TITLE
Resources stop working

### ISSUE THREAD

**Issue by Dragonir44** [lucianfialhobp/esx_inventory_hud#2]
i install the resource, it work perfectly but when i close the nui and open it again i have this error : 
![image](https://user-images.githubusercontent.com/69081570/99598508-e9bceb80-29f9-11eb-8ecc-01ad25f4362a.png)

**Comment by Dragonir44** [comment]
and it don't reopen

**Comment by MrFreex** [comment]
Same issue @lucianfialhobp

**Comment by lucianfialho** [comment]
Ok, iam working right now in this issue
